/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import automata.Automaton;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.SwingConstants;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author andrzej
 */
public class AutomataMainFrame extends javax.swing.JFrame {

	private void setNewAutomatonLabel(){
		String res;
		if(automatonNum < UPPERCASE.length()){
			res = UPPERCASE.substring(automatonNum,automatonNum+1);
		} else {
			res = "Z" + (automatonNum - UPPERCASE.length() + 1);
		}
		++automatonNum;
		newAutomatonLabel.setText(res + "=");
	}
	
	/**
	 * Creates new form AutomataMainFrame
	 */
	public AutomataMainFrame() {
		initComponents();
		automatons = new DefaultListModel<Automaton>();
		automatonList.setModel(automatons);
		newAutomatonLabel.setBorder(new EmptyBorder(0,5,0,0));
		setNewAutomatonLabel();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regExTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        automatonList = new javax.swing.JList<>();
        createAutomatonButton = new javax.swing.JButton();
        newAutomatonLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        regExTextField.setToolTipText("Wpisz wyrażenie regularne, z którego chcesz stworzyć automat.");
        regExTextField.setName("regExTextField"); // NOI18N

        outputTextArea.setEditable(false);
        outputTextArea.setColumns(20);
        outputTextArea.setRows(5);
        outputTextArea.setName(""); // NOI18N
        jScrollPane1.setViewportView(outputTextArea);

        automatonList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                automatonListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(automatonList);

        createAutomatonButton.setText("Stwórz");
        createAutomatonButton.setToolTipText("Tworzy automat z podanego obok wyrażenia regularnego.");
        createAutomatonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAutomatonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(newAutomatonLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(regExTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(createAutomatonButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(regExTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createAutomatonButton)
                            .addComponent(newAutomatonLabel))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAutomatonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAutomatonButtonActionPerformed
		String regEx = regExTextField.getText();
		System.out.println("RegEx: " + regEx);
		outputTextArea.setText("Tworzenie automatu z wyrażenia regularnego:\n>> " + regEx);
		try{
			Automaton a = new Automaton(regEx);
			a.setName(newAutomatonLabel.getText() + regEx);
			automatons.addElement(a);
			outputTextArea.setText(outputTextArea.getText() + "\n\nStworzono!");
			regExTextField.setText("");
			setNewAutomatonLabel();
		} catch(IllegalArgumentException e){
			outputTextArea.setText(outputTextArea.getText() + "\n\nBłąd: nieprawidłowe wyrażenie regularne!");
		}
    }//GEN-LAST:event_createAutomatonButtonActionPerformed

    private void automatonListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_automatonListValueChanged
		StringBuilder text = new StringBuilder();
		for(Automaton a : automatonList.getSelectedValuesList()){
			text.append(a.getName());
			text.append("\n--------------------\n");
			text.append(a.getPrint());
			text.append("====================\n\n");
		}
		outputTextArea.setText(text.toString());
    }//GEN-LAST:event_automatonListValueChanged

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(AutomataMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(AutomataMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(AutomataMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(AutomataMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AutomataMainFrame().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Automaton> automatonList;
    private javax.swing.JButton createAutomatonButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel newAutomatonLabel;
    private javax.swing.JTextArea outputTextArea;
    private javax.swing.JTextField regExTextField;
    // End of variables declaration//GEN-END:variables

	private DefaultListModel<Automaton> automatons;
	private int automatonNum = 0;
	
	private static final String UPPERCASE = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
}
